import { port, type NodeSpec } from "./types";

export const IMAGE_NODE_SPECS = {
  // Integrated production card gathering the image operations into one panel
  // of semantic rows (see NODE_CARD_PRODUCT_BOUNDARY_PLAN.md, "Image
  // Processing Card"). Each row has stable `row.in` / `row.out` port ids so
  // its connection dots sit on that row, and each row lowers at run time to
  // the corresponding internal leaf node (see graph/lowering.ts). Row params
  // are namespaced `<row>.<key>` and forwarded to the lowered node.
  imageProcessing: {
    kind: "imageProcessing",
    family: "image",
    executor: "compute",
    title: "Image Processing",
    description:
      "One production card for image operations, as semantic rows: Layer Split, Enhance, Grade, Crop / Transform, and Repair / Repaint. Connect to the row you want — each row exposes its own input/output dots and runs as the matching internal operation (Smart Layer Split, Image Enhance, Grade, Crop, Detail Repaint).",
    category: "process",
    inputs: [
      port("layerSplit.in", "Layer Split", "image"),
      port("enhance.in", "Enhance", "image"),
      port("grade.in", "Grade", "image"),
      port("crop.in", "Crop / Transform", "image"),
      port("repair.in", "Repair / Repaint", "image"),
      port("repair.report", "quality report", "any"),
    ],
    outputs: [
      port("layerSplit.out", "layered asset", "any"),
      port("enhance.out", "enhanced image", "image"),
      port("grade.out", "graded image", "image"),
      port("crop.out", "cropped image", "image"),
      port("repair.out", "repaired image", "image"),
    ],
    params: [
      {
        key: "layerSplit.selected_kind",
        label: "Layer Split: selected layer",
        control: "select",
        options: ["subject", "background", "original"],
        defaultValue: "subject",
        hint: "which layer the layerSplit.out row's asset marks as selected",
      },
      {
        key: "enhance.mode",
        label: "Enhance: mode",
        control: "select",
        options: ["conservative", "texture_rebuild", "custom"],
        defaultValue: "conservative",
      },
      {
        key: "grade.format",
        label: "Grade: output format",
        control: "select",
        options: ["png", "tiff"],
        defaultValue: "png",
      },
      {
        key: "crop.mode",
        label: "Crop: mode",
        control: "select",
        options: ["manual", "auto_subject"],
        defaultValue: "manual",
      },
      {
        key: "crop.aspect",
        label: "Crop: aspect",
        control: "select",
        options: ["free", "1:1", "4:3", "3:2", "16:9", "2:3", "3:4", "9:16"],
        defaultValue: "free",
      },
      {
        key: "repair.api_profile_ref",
        label: "Repair: API profile",
        control: "text",
        defaultValue: "",
        hint: "managed backend ref from the Models / APIs manager (set by the backend selector)",
        advanced: true,
      },
    ],
  },
  subjectMask: {
    kind: "subjectMask",
    family: "mask",
    executor: "compute",
    palette: "internal",
    title: "Subject Mask / Matte",
    description:
      "Select the subject and produce a mask / cutout / alpha triplet with deterministic built-in tools: point selection, magic-wand flood select, brush/eraser strokes, morphology, hole filling and feathering. Emits the mask, alpha image, cutout, trimap and matte report.",
    category: "process",
    inputs: [
      port("image", "image", "image"),
      port("reference", "reference", "image"),
      port("visual_context", "visual context", "any"),
      port("placeholder_mask", "placeholder mask", "image"),
      port("previous_mask", "previous mask", "image"),
      port("edit_paths", "edit paths", "any"),
    ],
    outputs: [
      port("mask", "mask", "image"),
      port("alpha_image", "alpha image", "image"),
      port("cutout_image", "cutout image", "image"),
      port("trimap", "trimap", "image"),
      port("matte_report", "matte report", "any"),
      port("edit_paths", "edit paths", "any"),
    ],
    params: [
      {
        key: "mode",
        label: "Mode",
        control: "select",
        options: [
          "hybrid",
          "manual_brush",
          "manual_pen",
          "auto_subject",
          "auto_product",
          "auto_person",
          "auto_transparent_object",
        ],
        defaultValue: "hybrid",
        inline: true,
        hint: "manual modes use authored strokes; auto modes use the deterministic built-in segmenter",
      },
      {
        key: "wand_tolerance",
        label: "Wand tolerance",
        control: "slider",
        min: 0,
        max: 255,
        step: 1,
        defaultValue: 24,
        hint: "colour distance for the magic-wand flood select",
      },
      {
        key: "grow_px",
        label: "Grow / shrink px",
        control: "slider",
        min: -16,
        max: 16,
        step: 1,
        defaultValue: 0,
        hint: "positive dilates the matte, negative erodes it",
      },
      {
        key: "fill_holes",
        label: "Fill holes",
        control: "checkbox",
        defaultValue: false,
        hint: "close enclosed interior gaps before feather",
      },
      {
        key: "feather_px",
        label: "Feather px",
        control: "slider",
        min: 0,
        max: 16,
        step: 1,
        defaultValue: 0,
        hint: "soften the matte edge (applied last)",
      },
      {
        key: "alpha_matting",
        label: "Alpha matting",
        control: "checkbox",
        defaultValue: false,
        hint: "resolve the binary edge into continuous alpha (hair / glass) with deterministic trimap feathering",
      },
      {
        key: "matting_band_px",
        label: "Matting band px",
        control: "slider",
        min: 0,
        max: 32,
        step: 1,
        defaultValue: 12,
        hint: "width of the trimap unknown band the matter resolves (only when alpha matting is on)",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the triplet PNGs (empty = <image>_mask)",
        inline: true,
      },
    ],
  },
  smartLayerSplit: {
    kind: "smartLayerSplit",
    family: "image",
    executor: "compute",
    palette: "internal",
    title: "Smart Layer Split",
    description:
      "Split the connected image into a LayeredImageAsset: a locked original layer plus background/subject candidates. A connected video is resolved to the still nearest the frame time first (desktop runtime only; the video input wins when both are connected). The desktop runtime uses the deterministic built-in segmenter and writes per-layer mask + RGBA PNGs; the browser preview keeps placeholder masks. Downstream nodes, the Review Editor, Grade and Timeline consume the layered_asset / layer ports.",
    category: "process",
    inputs: [port("image", "image", "image"), port("video", "video", "video")],
    outputs: [
      port("layered_asset", "layered asset", "any"),
      port("composite_preview", "composite preview", "image"),
      port("selected_layer", "selected layer", "image"),
      port("masks", "masks", "any"),
      port("split_report", "split report", "any"),
    ],
    params: [
      {
        key: "selected_kind",
        label: "Selected layer",
        control: "select",
        options: ["subject", "background", "original"],
        defaultValue: "subject",
        inline: true,
        hint: "which layer the selected_layer output emits",
      },
      {
        key: "instancing",
        label: "Instancing",
        control: "select",
        options: ["off", "auto"],
        defaultValue: "off",
        inline: true,
        hint: "auto splits the subject mask into per-object instance layers (connected components, largest first) — desktop runtime only; every instance is flagged for review",
      },
      {
        key: "detect_text",
        label: "Detect text",
        control: "checkbox",
        defaultValue: false,
        hint: "detect likely text lines as protected text layer candidates (heuristic edge-density detector) — desktop runtime only; every region is flagged for review",
      },
      {
        key: "detect_logo",
        label: "Detect logo",
        control: "checkbox",
        defaultValue: false,
        hint: "detect compact high-contrast marks near the canvas border as protected logo layer candidates (heuristic) — desktop runtime only; every region is flagged for review",
      },
      {
        key: "detect_shadow",
        label: "Detect shadow",
        control: "checkbox",
        defaultValue: false,
        hint: "detect a cast-shadow candidate next to the subject (background regions darker than the background baseline) as its own layer — desktop runtime only; flagged for review",
      },
      {
        key: "detect_reflection",
        label: "Detect reflection",
        control: "checkbox",
        defaultValue: false,
        hint: "detect a reflection candidate below the subject (a dimmer vertically mirrored copy on the surface) as its own layer — desktop runtime only; flagged for review",
      },
      {
        key: "frame_sec",
        label: "Frame time (s)",
        control: "number",
        defaultValue: 0,
        hint: "timestamp of the still to split when a video is connected, in seconds — desktop runtime only",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the per-layer PNGs (empty = <image>_split)",
        inline: true,
      },
    ],
  },
  crop: {
    kind: "crop",
    family: "crop",
    executor: "compute",
    palette: "internal",
    title: "Crop",
    description:
      "Crop an image: the first non-masking image edit, validating the unified auto/manual + binding model. Runs in-process in native Rust on the Compute lane. Manual mode crops to the editor-drawn box (recorded as crop_box in image pixels, the human-spatial-intent lane); auto_subject mode crops to the subject: it segments a base matte with the same Subject Mask Compute-lane segmenter, takes its bounding box and pads it by the subject margin (the algorithm-derived lane). An optional aspect ratio adjusts the box (centred, clamped to the image) after either lane. Emits the cropped image and a crop report.",
    category: "process",
    inputs: [port("image", "image", "image")],
    outputs: [port("image", "image", "image"), port("crop_report", "crop report", "any")],
    params: [
      {
        key: "mode",
        label: "Mode",
        control: "select",
        options: ["manual", "auto_subject"],
        defaultValue: "manual",
        inline: true,
        hint: "manual crops to the box drawn in the editor; auto_subject crops to the detected subject",
      },
      {
        key: "aspect",
        label: "Aspect",
        control: "select",
        options: ["free", "1:1", "4:3", "3:2", "16:9", "2:3", "3:4", "9:16"],
        defaultValue: "free",
        inline: true,
        hint: "lock the crop to an aspect ratio (centred, clamped to the image); free keeps the box as drawn",
      },
      {
        key: "margin_pct",
        label: "Subject margin %",
        control: "slider",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 6,
        visibleWhen: { param: "mode", in: ["auto_subject"] },
        hint: "padding kept around the detected subject (auto_subject mode only)",
      },
      {
        key: "format",
        label: "Output format",
        control: "select",
        options: ["png", "tiff"],
        defaultValue: "png",
        inline: true,
        hint: "png (default) or 16-bit tiff; a wide-gamut source keeps 16-bit + ICC in either",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the cropped output (empty = <image>_crop)",
        inline: true,
      },
    ],
  },
  imageGrade: {
    kind: "imageGrade",
    family: "grade",
    executor: "compute",
    palette: "internal",
    title: "Grade",
    description:
      "Colour-grade an image with the hgripe-grade kernel (docs/design/grade-kernel.md): an op stack for exposure, white balance, contrast, saturation, RGB mixing, colour warping, sharpening, denoise, grain and vignette. The dialog previews live through the kernel; the run path grades the full-resolution 16-bit working surface in its own colour space. Emits the graded image and a grade report.",
    category: "process",
    inputs: [port("image", "image", "image")],
    outputs: [port("image", "image", "image"), port("grade_report", "grade report", "any")],
    params: [
      {
        key: "format",
        label: "Output format",
        control: "select",
        options: ["png", "tiff"],
        defaultValue: "png",
        inline: true,
        hint: "png (default) or 16-bit tiff; a wide-gamut source keeps 16-bit + ICC in either",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the graded output (empty = <image>_grade)",
        inline: true,
      },
    ],
  },
} satisfies Record<string, NodeSpec>;
