import { port, type NodeSpec } from "./types";
import {
  IMAGE_ENHANCE_DEVICE_OPTIONS,
  IMAGE_ENHANCE_ENGINE_OPTIONS,
  IMAGE_ENHANCE_PRECISION_OPTIONS,
} from "../../contracts/imageEnhance";

export const PSD_NODE_SPECS = {
  psdContextAnalyze: {
    kind: "psdContextAnalyze",
    family: "psd",
    executor: "local",
    title: "PSD Context Analyze",
    description:
      "Read a PSD template into a structured visual context: background colour & lighting heuristics, placeholder geometry + safe area, a placeholder mask & background preview, and a prompt suffix for downstream generation.",
    category: "process",
    inputs: [port("template", "template", "any")],
    outputs: [
      port("visual_context", "visual context", "any"),
      port("prompt_suffix", "prompt suffix", "text"),
      port("background_image", "background", "image"),
      port("placeholder_mask", "placeholder mask", "image"),
      port("placeholder_bounds", "placeholder bounds", "any"),
    ],
    params: [
      {
        key: "psd_path",
        label: "PSD path",
        control: "path",
        defaultValue: "",
        hint: "used when no PSD Template node is connected",
        pickerFilterName: "PSD",
        pickerExtensions: ["psd"],
      },
      {
        key: "background_layer",
        label: "Background layer",
        control: "text",
        defaultValue: "",
        hint: "layer to sample (empty = composite the whole PSD)",
        inline: true,
      },
      {
        key: "target_placeholder",
        label: "Placeholder layer",
        control: "text",
        defaultValue: "",
        hint: "placeholder to measure (empty = whole canvas)",
        inline: true,
      },
      {
        key: "reference_layers",
        label: "Reference layers",
        control: "textarea",
        defaultValue: "",
        hint: "one layer name per line (advisory in Phase 1)",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
    ],
  },
  matchLightColor: {
    kind: "matchLightColor",
    family: "grade",
    executor: "local",
    title: "Light & Color Match",
    description:
      "Nudge a generated subject's light & colour toward the PSD background so the composite stops looking pasted-on: Reinhard Lab transfer / histogram match weighted toward shadows & highlights, sparing brand colours. Emits the matched image, a match report, and a prompt suffix.",
    category: "process",
    inputs: [
      port("image", "image", "image"),
      port("visual_context", "visual context", "any"),
      port("background", "background", "image"),
      port("mask", "mask", "image"),
    ],
    outputs: [
      port("matched_image", "matched image", "image"),
      port("match_report", "match report", "any"),
      port("prompt_suffix", "prompt suffix", "text"),
    ],
    params: [
      {
        key: "mode",
        label: "Mode",
        control: "select",
        options: ["prompt_only", "color_transfer", "histogram_match", "hybrid"],
        defaultValue: "color_transfer",
        inline: true,
      },
      {
        key: "engine",
        label: "Engine",
        control: "select",
        options: ["cpu", "onnx_harmonize"],
        defaultValue: "cpu",
        inline: true,
        hint: "cpu = built-in Lab transfer / histogram match (always available); onnx_harmonize = native PCT-Net through ONNX Runtime, with cpu fallback when its weight/runtime/inference is unavailable",
        visibleWhen: { param: "mode", in: ["color_transfer", "histogram_match", "hybrid"] },
      },
      {
        key: "device",
        label: "Device",
        control: "select",
        options: ["auto", "gpu", "cpu"],
        defaultValue: "auto",
        inline: true,
        hint: "compute request for native PCT-Net: auto | gpu | cpu. The current ONNX Runtime path is CPU-only; CUDA and DirectML providers are planned. Ignored by the cpu heuristic",
        visibleWhen: { param: "engine", in: ["onnx_harmonize"] },
      },
      {
        key: "strength",
        label: "Strength",
        control: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.6,
        inline: true,
        visibleWhen: { param: "mode", in: ["color_transfer", "histogram_match", "hybrid"] },
      },
      {
        key: "shadow_strength",
        label: "Shadow strength",
        control: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        hint: "extra correction weight in shadows",
        visibleWhen: { param: "mode", in: ["color_transfer", "histogram_match", "hybrid"] },
      },
      {
        key: "highlight_strength",
        label: "Highlight strength",
        control: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        hint: "extra correction weight in highlights",
        visibleWhen: { param: "mode", in: ["color_transfer", "histogram_match", "hybrid"] },
      },
      {
        key: "protect_brand_color",
        label: "Protect brand colour",
        control: "checkbox",
        defaultValue: true,
        hint: "damp the shift on high-chroma (brand) pixels so logos/packaging keep their colour",
        visibleWhen: { param: "mode", in: ["color_transfer", "histogram_match", "hybrid"] },
      },
      {
        key: "protect_saturation",
        label: "Protect saturation",
        control: "checkbox",
        defaultValue: false,
        hint: "match luminance only, keeping the subject's own chroma",
        visibleWhen: { param: "mode", in: ["color_transfer", "histogram_match", "hybrid"] },
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the matched PNG (empty = <image>_matched)",
        inline: true,
      },
    ],
  },
  refineMaskEdge: {
    kind: "refineMaskEdge",
    family: "mask",
    executor: "local",
    palette: "internal",
    title: "Mask Edge Refine",
    description:
      "Clean a cut-out subject's matte so it drops into a PSD placeholder without white halos or fringing: erode/dilate morphology, guided-filter edge snapping, feather, and edge colour decontamination. Connect the Subject Mask 'trimap' output to protect its unknown band (hair / fur / glass continuous alpha) from the erode/feather clean-up so fine detail survives. Emits the refined image, refined mask, and an edge report. Presets hide the detail; pick 'custom' to expose every parameter.",
    category: "process",
    inputs: [
      port("image", "image", "image"),
      port("mask", "mask", "image"),
      port("background", "background", "image"),
      port("placeholder_mask", "placeholder mask", "image"),
      port("trimap", "trimap", "image"),
    ],
    outputs: [
      port("refined_image", "refined image", "image"),
      port("refined_mask", "refined mask", "image"),
      port("edge_report", "edge report", "any"),
    ],
    params: [
      {
        key: "preset",
        label: "Preset",
        control: "select",
        options: ["clean", "natural", "soft", "custom"],
        defaultValue: "natural",
        inline: true,
        hint: "clean = tight 1px bite, natural = soft 6px feather, soft = no bite, custom = expose all",
      },
      {
        key: "local_model_ref",
        label: "Local model",
        control: "text",
        defaultValue: "",
        hint: "managed local model ref from the Models / APIs manager (set by the backend selector)",
        advanced: true,
      },
      {
        key: "engine",
        label: "Engine",
        control: "select",
        options: ["cpu", "onnx_matting"],
        defaultValue: "cpu",
        inline: true,
        hint: "cpu = built-in heuristic refine (always available); onnx_matting = opt-in learned matter, needs a connected trimap and falls back to cpu when its weight/deps are missing",
      },
      {
        key: "device",
        label: "Device",
        control: "select",
        options: ["auto", "gpu", "cpu"],
        defaultValue: "auto",
        inline: true,
        hint: "compute request for native ViTMatte: auto | gpu | cpu. The current ONNX Runtime path is CPU-only; CUDA and DirectML providers are planned. Ignored by the cpu heuristic",
        visibleWhen: { param: "engine", in: ["onnx_matting"] },
      },
      {
        key: "erode_px",
        label: "Erode px",
        control: "slider",
        min: 0,
        max: 4,
        step: 1,
        defaultValue: 1,
        hint: "bite the matte inward to cut white fringe",
        visibleWhen: { param: "preset", in: ["custom"] },
      },
      {
        key: "dilate_px",
        label: "Dilate px",
        control: "slider",
        min: 0,
        max: 4,
        step: 1,
        defaultValue: 0,
        hint: "grow the matte outward",
        visibleWhen: { param: "preset", in: ["custom"] },
      },
      {
        key: "feather_px",
        label: "Feather px",
        control: "slider",
        min: 0,
        max: 16,
        step: 1,
        defaultValue: 4,
        hint: "soften the edge transition",
        visibleWhen: { param: "preset", in: ["custom"] },
      },
      {
        key: "guided_radius",
        label: "Guided radius",
        control: "slider",
        min: 0,
        max: 16,
        step: 1,
        defaultValue: 8,
        hint: "snap the matte to luminance edges (0 disables)",
        visibleWhen: { param: "preset", in: ["custom"] },
      },
      {
        key: "edge_decontaminate",
        label: "Edge decontaminate",
        control: "checkbox",
        defaultValue: true,
        hint: "bleed opaque subject colour into the edge band to kill residual fringe",
        visibleWhen: { param: "preset", in: ["custom"] },
      },
      {
        key: "background_blend_strength",
        label: "Background blend",
        control: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.4,
        hint: "blend the edge band toward the connected background colour",
        visibleWhen: { param: "preset", in: ["custom"] },
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the refined PNGs (empty = <image>_refined)",
        inline: true,
      },
    ],
  },
  imageEnhance: {
    kind: "imageEnhance",
    family: "compute",
    executor: "local",
    palette: "internal",
    title: "Image Enhance",
    description:
      "Upscale a low-resolution subject so it fills a PSD placeholder crisply at print DPI. The built-in CPU path uses Lanczos and sharpening; native Real-ESRGAN provides model-based super-resolution and currently runs on CPU in FP32. Connect placeholder bounds to auto-size, or set explicit target pixels. Emits the enhanced image, the applied scale factor, and an enhance report. Presets hide the detail; pick 'custom' to expose denoise/texture/scale.",
    category: "process",
    inputs: [
      port("image", "image", "image"),
      port("target_bounds", "target bounds", "any"),
    ],
    outputs: [
      port("enhanced_image", "enhanced image", "image"),
      port("scale_factor", "scale factor", "number"),
      port("enhance_report", "enhance report", "any"),
    ],
    params: [
      {
        key: "mode",
        label: "Mode",
        control: "select",
        options: ["conservative", "texture_rebuild", "print_ready", "custom"],
        defaultValue: "conservative",
        inline: true,
        hint: "conservative = gentle, texture_rebuild = strong detail, print_ready = balanced, custom = expose sliders",
      },
      {
        key: "local_model_ref",
        label: "Local model",
        control: "text",
        defaultValue: "",
        hint: "managed local model ref from the Models / APIs manager (set by the backend selector)",
        advanced: true,
      },
      {
        key: "engine",
        label: "Engine",
        control: "select",
        options: [...IMAGE_ENHANCE_ENGINE_OPTIONS],
        defaultValue: "cpu",
        inline: true,
        hint: "cpu = built-in Lanczos+sharpen (always available); realesrgan = native model super-resolution, currently CPU/FP32, with fallback to cpu when its model is missing",
      },
      {
        key: "device",
        label: "Device",
        control: "select",
        options: [...IMAGE_ENHANCE_DEVICE_OPTIONS],
        defaultValue: "auto",
        inline: true,
        hint: "compute request for native Real-ESRGAN: auto | gpu | cpu. The current path is CPU-only; CUDA and DirectML are planned. Ignored by the cpu path",
        visibleWhen: { param: "engine", in: ["realesrgan"] },
      },
      {
        key: "precision",
        label: "Precision",
        control: "select",
        options: [...IMAGE_ENHANCE_PRECISION_OPTIONS],
        defaultValue: "auto",
        inline: true,
        hint: "compute precision for native Real-ESRGAN: auto currently resolves to fp32; fp16 is not available. Ignored by the cpu path",
        visibleWhen: { param: "engine", in: ["realesrgan"] },
      },
      {
        key: "target_width",
        label: "Target width",
        control: "slider",
        min: 0,
        max: 8192,
        step: 1,
        defaultValue: 0,
        hint: "explicit target px (0 = auto from connected bounds or preset scale)",
      },
      {
        key: "target_height",
        label: "Target height",
        control: "slider",
        min: 0,
        max: 8192,
        step: 1,
        defaultValue: 0,
        hint: "explicit target px (0 = auto from connected bounds or preset scale)",
      },
      {
        key: "target_dpi",
        label: "Target DPI",
        control: "slider",
        min: 72,
        max: 600,
        step: 1,
        defaultValue: 300,
        hint: "DPI written into the output PNG metadata",
      },
      {
        key: "scale",
        label: "Scale",
        control: "slider",
        min: 1,
        max: 8,
        step: 0.25,
        defaultValue: 2,
        hint: "upscale factor when no target size is given",
        visibleWhen: { param: "mode", in: ["custom"] },
      },
      {
        key: "denoise_strength",
        label: "Denoise",
        control: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.3,
        hint: "edge-preserving median denoise blend before upscaling",
        visibleWhen: { param: "mode", in: ["custom"] },
      },
      {
        key: "texture_strength",
        label: "Texture",
        control: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.25,
        hint: "unsharp-mask detail strength after upscaling",
        visibleWhen: { param: "mode", in: ["custom"] },
      },
      {
        key: "max_pixels",
        label: "Max pixels",
        control: "slider",
        min: 1000000,
        max: 96000000,
        step: 1000000,
        defaultValue: 48000000,
        hint: "cap output pixels; scale is reduced to fit",
        visibleWhen: { param: "mode", in: ["custom"] },
      },
      {
        key: "preserve_text_logo",
        label: "Preserve text/logo",
        control: "checkbox",
        defaultValue: true,
        hint: "cap sharpening so logos / packaging text are not mangled",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the enhanced PNG (empty = <image>_enhanced)",
        inline: true,
      },
    ],
  },
} satisfies Record<string, NodeSpec>;
