import { port, type NodeSpec } from "./types";

export const QUALITY_NODE_SPECS = {
  detailWatchdog: {
    kind: "detailWatchdog",
    family: "compute",
    executor: "local",
    title: "Detail Watchdog",
    description:
      "Scan a candidate image for local breakdowns and emit a QualityReport. Detect-only: 'fixed_image' is unchanged. Native CPU rules always cover blur, alpha-rim halos, colour mismatch and target resolution; optional onnx_defect adds sidecar-mapped hands/text/logo findings and keeps the full rules report on fallback. Connect a VisualContext and/or placeholder bounds for resolution and colour checks.",
    category: "review",
    inputs: [
      port("image", "image", "image"),
      port("visual_context", "visual context", "any"),
      port("target_bounds", "target bounds", "any"),
    ],
    outputs: [
      port("fixed_image", "fixed image", "image"),
      port("quality_report", "quality report", "any"),
      port("issue_masks", "issue masks", "image"),
      port("watchdog_report", "watchdog report", "any"),
    ],
    params: [
      {
        key: "mode",
        label: "Mode",
        control: "select",
        options: ["strict", "balanced", "lenient"],
        defaultValue: "balanced",
        inline: true,
        hint: "detection sensitivity: strict = flags more, lenient = flags less",
      },
      {
        key: "watch_targets",
        label: "Watch targets",
        control: "text",
        defaultValue: "",
        hint: "comma list of face,hands,text,logo,product_edges (empty = all); hands/text/logo are skipped unless an ML engine covers them",
      },
      {
        key: "engine",
        label: "Engine",
        control: "select",
        options: ["rules", "onnx_defect"],
        defaultValue: "rules",
        inline: true,
        hint: "rules = built-in CPU rule layer (always available); onnx_defect = native ORT detector for hands/text/logo, preserving rules output when its runtime, weight or inference is unavailable",
      },
      {
        key: "device",
        label: "Device",
        control: "select",
        options: ["auto", "gpu", "cpu"],
        defaultValue: "auto",
        inline: true,
        hint: "compute request for onnx_defect: auto | gpu | cpu. The current Windows ORT path is CPU-only; CUDA and DirectML providers are planned. Ignored by rules",
        visibleWhen: { param: "engine", in: ["onnx_defect"] },
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the issue-overlay PNG (empty = <image>_issues)",
        inline: true,
      },
    ],
  },
  detailRepaint: {
    kind: "detailRepaint",
    family: "compute",
    executor: "api",
    palette: "internal",
    title: "Detail Repaint",
    description:
      "Localized repaint of the issue regions a Detail Watchdog flagged. Crops each repaintable issue (suggested_action in 'Repaint actions') with padding, writes an inpaint mask, sends each crop through the broker's image.edit operation (same provider/credentials path as Generate), then pastes the results back with a feathered seam. Outputs the fixed image and a RepaintReport. With no edit-capable provider configured (empty / 'mock') every region is left unrepainted and the image passes through unchanged.",
    category: "process",
    inputs: [
      port("image", "image", "image"),
      port("quality_report", "quality report", "any"),
    ],
    outputs: [
      port("fixed_image", "fixed image", "image"),
      port("repaint_report", "repaint report", "any"),
    ],
    params: [
      {
        key: "api_profile_ref",
        label: "API profile",
        control: "text",
        defaultValue: "",
        hint: "managed backend ref from the Models / APIs manager (set by the backend selector)",
        advanced: true,
      },
      {
        key: "local_model_ref",
        label: "Local model",
        control: "text",
        defaultValue: "",
        hint: "managed local model ref from the Models / APIs manager (set by the backend selector)",
        advanced: true,
      },
      {
        key: "provider",
        label: "Provider",
        control: "text",
        defaultValue: "mock",
        hint: "an image.edit-capable provider (set automatically when you pick a profile); empty/mock passes through",
        advanced: true,
      },
      {
        key: "operation",
        label: "Operation",
        control: "select",
        options: ["image.edit"],
        defaultValue: "image.edit",
        inline: true,
      },
      {
        key: "engine",
        label: "Engine",
        control: "select",
        options: ["provider", "sd_inpaint", "sdxl_inpaint", "flux_fill"],
        defaultValue: "provider",
        inline: true,
        hint: "provider = remote image.edit (default); sd_inpaint / sdxl_inpaint / flux_fill = opt-in local GPU inpaint, falls back to the provider when its weights/deps are missing (flux_fill ignores negative prompt and strength)",
      },
      {
        key: "precision",
        label: "Precision",
        control: "select",
        options: ["auto", "fp32", "fp16"],
        defaultValue: "auto",
        inline: true,
        hint: "compute precision for the local inpaint backends: auto (fp16 on cuda else fp32) | fp32 | fp16 (degrades to fp32 on a cpu run); ignored by the provider path",
        visibleWhen: { param: "engine", in: ["sd_inpaint", "sdxl_inpaint", "flux_fill"] },
      },
      {
        key: "controlnet",
        label: "ControlNet",
        control: "select",
        options: ["off", "canny"],
        defaultValue: "off",
        inline: true,
        hint: "structural conditioning for sd_inpaint: off (default) | canny (edge-conditioned repaint keeps structure stable; needs the HGRIPE_CONTROLNET_MODEL weight, falls back to the provider when missing)",
        visibleWhen: { param: "engine", in: ["sd_inpaint"] },
      },
      {
        key: "credentials_ref",
        label: "Credentials",
        control: "text",
        defaultValue: "",
        hint: "set automatically when you pick a profile",
        advanced: true,
      },
      {
        key: "repaint_prompt_base",
        label: "Repaint prompt",
        control: "text",
        defaultValue: "",
        hint: "base prompt for each region (empty = a generic restore prompt; the issue type is appended)",
      },
      {
        key: "repaint_actions",
        label: "Repaint actions",
        control: "text",
        defaultValue: "detail_redraw",
        hint: "comma list of suggested_action values to repaint",
        inline: true,
      },
      {
        key: "min_confidence",
        label: "Min confidence",
        control: "number",
        defaultValue: 0,
        hint: "only repaint issues at/above this confidence (0..1)",
        inline: true,
      },
      {
        key: "region_padding",
        label: "Region padding",
        control: "number",
        defaultValue: 24,
        hint: "context padding (px) added around each issue box",
        inline: true,
      },
      {
        key: "max_regions",
        label: "Max regions",
        control: "number",
        defaultValue: 8,
        hint: "cap how many regions are repainted (highest confidence first)",
        inline: true,
      },
      {
        key: "feather_px",
        label: "Feather px",
        control: "number",
        defaultValue: 0,
        hint: "seam feather radius (0 = auto from the issue size); ignored by the poisson blend",
        inline: true,
      },
      {
        key: "blend",
        label: "Seam blend",
        control: "select",
        options: ["feather", "poisson"],
        defaultValue: "feather",
        inline: true,
        hint: "feather = soft alpha falloff at the patch seam (default); poisson = gradient-domain seamless clone for harder seams (falls back to feather on a too-small region)",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "base name for the fixed image (empty = <image>_repainted)",
        inline: true,
      },
    ],
  },
} satisfies Record<string, NodeSpec>;
