import { port, type NodeSpec } from "./types";
import { IMAGE_MEDIA_EXTS } from "../../domain/mediaFormats";

export const SOURCE_NODE_SPECS = {
  promptOptimize: {
    kind: "promptOptimize",
    family: "utility",
    executor: "hybrid",
    title: "Prompt",
    description:
      "A text prompt fed into generation nodes. Optionally pick a model to optimize it — the built-in local presets, or a local model / API profile from the Models / APIs manager. Leave the model empty to pass the text through unchanged.",
    category: "source",
    inputs: [port("text", "text", "text")],
    outputs: [port("text", "text", "text")],
    params: [
      {
        key: "text",
        label: "Prompt",
        control: "textarea",
        defaultValue: "",
        hint: "the initial prompt (a connected `text` input overrides this)",
        inline: true,
        port: "text",
      },
      {
        key: "mode",
        label: "Optimize",
        control: "select",
        options: ["off", "local", "api"],
        defaultValue: "off",
        hint: "off = pass through · local = rule-based · api = LLM via profile (set by the model dropdown)",
        advanced: true,
      },
      {
        key: "preset",
        label: "Local preset",
        control: "select",
        options: ["cleanup", "photographic", "anime", "cinematic", "detailed"],
        defaultValue: "cleanup",
        hint: "used by `local` mode: dedupe + append booster tags",
        visibleWhen: { param: "mode", in: ["local"] },
      },
      {
        key: "api_profile_ref",
        label: "API profile",
        control: "text",
        defaultValue: "",
        hint: "managed backend ref from the Models / APIs manager (set by the backend selector)",
        visibleWhen: { param: "mode", in: ["api"] },
        advanced: true,
      },
      {
        key: "provider",
        label: "Provider",
        control: "text",
        defaultValue: "openai_compatible",
        hint: "used by `api` mode (set automatically when you pick a profile)",
        visibleWhen: { param: "mode", in: ["api"] },
        advanced: true,
      },
      {
        key: "model",
        label: "Model",
        control: "text",
        defaultValue: "",
        hint: "used by `api` mode",
        visibleWhen: { param: "mode", in: ["api"] },
        advanced: true,
      },
      {
        key: "instruction",
        label: "Instruction",
        control: "textarea",
        defaultValue:
          "Rewrite the text below into a single high-quality English image-generation prompt. Keep the original intent, add useful visual detail, and output only the prompt.",
        hint: "used by `api` mode (sent as the system prompt)",
        visibleWhen: { param: "mode", in: ["api"] },
      },
      {
        key: "credentials_ref",
        label: "Credentials",
        control: "text",
        defaultValue: "",
        hint: "used by `api` mode (set automatically when you pick a profile)",
        visibleWhen: { param: "mode", in: ["api"] },
        advanced: true,
      },
      {
        key: "temperature",
        label: "Temperature",
        control: "number",
        defaultValue: "",
        min: 0,
        max: 2,
        step: 0.1,
        hint: "used by `api` mode (optional): sampling randomness, leave blank for provider default",
        visibleWhen: { param: "mode", in: ["api"] },
      },
      {
        key: "max_tokens",
        label: "Max tokens",
        control: "number",
        defaultValue: "",
        min: 1,
        step: 1,
        hint: "used by `api` mode (optional): cap the optimized prompt length",
        visibleWhen: { param: "mode", in: ["api"] },
      },
      {
        key: "seed",
        label: "Seed",
        control: "number",
        defaultValue: "",
        step: 1,
        hint: "used by `api` mode (optional): fix for reproducible output",
        visibleWhen: { param: "mode", in: ["api"] },
      },
    ],
  },
  imageSource: {
    kind: "imageSource",
    family: "image",
    executor: "graph",
    title: "Image Source",
    description: "An image file on disk, used as a reference / input image.",
    category: "source",
    inputs: [],
    outputs: [port("image", "image", "image")],
    params: [
      {
        key: "path",
        label: "Image path",
        control: "path",
        defaultValue: "",
        hint: "absolute path to an image file",
        inline: true,
        pickerFilterName: "Images",
        pickerExtensions: [...IMAGE_MEDIA_EXTS],
      },
    ],
  },
  videoSource: {
    kind: "videoSource",
    family: "video",
    executor: "graph",
    title: "Video Source",
    description: "A video file on disk; shows a poster frame and carries the path downstream.",
    category: "source",
    inputs: [],
    outputs: [port("video", "video", "video")],
    params: [
      {
        key: "path",
        label: "Video path",
        control: "path",
        defaultValue: "",
        hint: "absolute path to a video file",
        inline: true,
        pickerFilterName: "Videos",
        pickerExtensions: ["mp4", "mov", "mkv", "webm", "avi", "m4v"],
      },
      {
        key: "poster_timestamp",
        label: "Poster time (s)",
        control: "number",
        defaultValue: 0,
        hint: "timestamp of the poster frame, in seconds",
      },
    ],
  },
  psdTemplate: {
    kind: "psdTemplate",
    family: "psd",
    executor: "graph",
    title: "PSD Template",
    description: "A .psd template path carried through to export.",
    category: "source",
    inputs: [],
    outputs: [port("template", "template", "any")],
    params: [
      {
        key: "path",
        label: "Template path",
        control: "path",
        defaultValue: "",
        hint: "absolute path to a .psd template",
        inline: true,
        pickerFilterName: "PSD",
        pickerExtensions: ["psd"],
      },
    ],
  },
} satisfies Record<string, NodeSpec>;
