import { port, type NodeSpec } from "./types";

export const VIDEO_NODE_SPECS = {
  // Integrated production card for the video operations, following the same
  // data-driven contract as Image Processing: `row.in` / `row.out` port ids
  // keep each row's dots on its row, params are namespaced `<row>.<key>`, and
  // graph/lowering.ts (LOWERED_CARD_ROWS) expands each wired row into the
  // matching internal leaf node at run time.
  videoProcessing: {
    kind: "videoProcessing",
    family: "video",
    executor: "local",
    title: "Video Processing",
    description:
      "One production card for video operations, as semantic rows: Assemble (encode a frame sequence into a video) and Trim (cut a time range out of a clip). Connect to the row you want — each row exposes its own input/output dots and runs as the matching internal operation (Video Assemble, Video Trim).",
    category: "process",
    inputs: [
      port("assemble.in", "Assemble frames", "any"),
      port("trim.in", "Trim", "video"),
    ],
    outputs: [
      port("assemble.out", "assembled video", "video"),
      port("trim.out", "trimmed video", "video"),
    ],
    params: [
      {
        key: "assemble.fps",
        label: "Assemble: FPS",
        control: "number",
        min: 1,
        max: 240,
        step: 1,
        defaultValue: 24,
        hint: "output frame rate",
      },
      {
        key: "assemble.codec",
        label: "Assemble: codec",
        control: "select",
        options: ["libx264", "libx265", "mpeg4"],
        defaultValue: "libx264",
        hint: "ffmpeg encoder; libx264 is the most compatible",
      },
      {
        key: "trim.start_sec",
        label: "Trim: start sec",
        control: "number",
        min: 0,
        step: 0.1,
        defaultValue: 0,
        hint: "cut start (seconds from the beginning)",
      },
      {
        key: "trim.end_sec",
        label: "Trim: end sec",
        control: "number",
        min: 0,
        step: 0.1,
        defaultValue: 0,
        hint: "cut end in seconds (0 = to the end of the clip)",
      },
      {
        key: "trim.codec",
        label: "Trim: codec",
        control: "select",
        options: ["libx264", "libx265", "mpeg4"],
        defaultValue: "libx264",
        hint: "ffmpeg encoder for the re-encode; libx264 is the most compatible",
      },
    ],
  },
  videoAssemble: {
    kind: "videoAssemble",
    family: "video",
    executor: "local",
    palette: "internal",
    title: "Video Assemble",
    description:
      "Encode an ordered frame-image sequence into a video file through the media engine's vendored native FFmpeg backend. Connect a frames list (or set the frames param, one path per line), pick fps and codec, and get an .mp4 on disk plus the encode report.",
    category: "output",
    inputs: [port("frames", "frames", "any")],
    outputs: [
      port("video", "video", "video"),
      port("frame_count", "frame count", "number"),
      port("duration_sec", "duration sec", "number"),
      port("assemble_report", "assemble report", "any"),
    ],
    params: [
      {
        key: "frames",
        label: "Frames",
        control: "textarea",
        defaultValue: "",
        hint: "frame image paths, one per line (a connected frames input overrides this)",
      },
      {
        key: "fps",
        label: "FPS",
        control: "number",
        min: 1,
        max: 240,
        step: 1,
        defaultValue: 24,
        inline: true,
        hint: "output frame rate",
      },
      {
        key: "codec",
        label: "Codec",
        control: "select",
        options: ["libx264", "libx265", "mpeg4"],
        defaultValue: "libx264",
        inline: true,
        hint: "ffmpeg encoder; libx264 is the most compatible",
      },
      {
        key: "device",
        label: "Device",
        control: "select",
        options: ["auto", "cpu", "gpu"],
        defaultValue: "auto",
        inline: true,
        hint: "gpu tries a hardware H.264 encoder (nvenc/qsv/amf/mf) and falls back to software encode with a visible reason; auto/cpu use software encode",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "output file name (empty = assembled-<timestamp>.mp4; extension defaults to .mp4)",
        inline: true,
      },
    ],
  },
  videoTrim: {
    kind: "videoTrim",
    family: "video",
    executor: "local",
    palette: "internal",
    title: "Video Trim",
    description:
      "Cut a time range out of a video file through the media engine's vendored native FFmpeg backend. Connect a video (or set the video param), pick start/end seconds, and get a frame-accurate re-encoded clip on disk plus the trim report. Audio is not carried over.",
    category: "output",
    inputs: [port("video", "video", "video")],
    outputs: [
      port("video", "video", "video"),
      port("frame_count", "frame count", "number"),
      port("duration_sec", "duration sec", "number"),
      port("trim_report", "trim report", "any"),
    ],
    params: [
      {
        key: "video",
        label: "Video",
        control: "path",
        defaultValue: "",
        hint: "source video path (a connected video input overrides this)",
      },
      {
        key: "start_sec",
        label: "Start sec",
        control: "number",
        min: 0,
        step: 0.1,
        defaultValue: 0,
        inline: true,
        hint: "cut start (seconds from the beginning)",
      },
      {
        key: "end_sec",
        label: "End sec",
        control: "number",
        min: 0,
        step: 0.1,
        defaultValue: 0,
        inline: true,
        hint: "cut end in seconds (0 = to the end of the clip)",
      },
      {
        key: "codec",
        label: "Codec",
        control: "select",
        options: ["libx264", "libx265", "mpeg4"],
        defaultValue: "libx264",
        inline: true,
        hint: "ffmpeg encoder for the re-encode; libx264 is the most compatible",
      },
      {
        key: "device",
        label: "Device",
        control: "select",
        options: ["auto", "cpu", "gpu"],
        defaultValue: "auto",
        inline: true,
        hint: "gpu tries a hardware H.264 encoder (nvenc/qsv/amf/mf) and falls back to software encode with a visible reason; auto/cpu use software encode",
      },
      {
        key: "output_dir",
        label: "Output dir",
        control: "path",
        defaultValue: "",
        hint: "leave empty to use the configured output directory",
      },
      {
        key: "output_name",
        label: "Output name",
        control: "text",
        defaultValue: "",
        hint: "output file name (empty = trimmed-<timestamp>.mp4; extension defaults to .mp4)",
        inline: true,
      },
    ],
  },
} satisfies Record<string, NodeSpec>;
